---
:mailboxes:
  -
    :email: "csc322emailarchive@gmail.com"
    :password: "password12345"
    :name: "inbox"
    :delivery_method: postback
    :delivery_options:
#        :delivery_url: "https://mail-project-lederman17.c9users.io"
        :delivery_url "http://localhost:3000/inbox"
        :delivery_token: "password12345"